SELECT * FROM EMP;

--사원번호가 7934인 사원정보는?
SELECT * FROM EMP
WHERE EMPNO = 7934;

SELECT * FROM EMP
WHERE EMPNO = 7984;

SELECT * FROM EMP
WHERE EMPNO = 7934;

SELECT * FROM EMP
WHERE EMPNO BETWEEN 500 AND 9000;

SELECT EMPNO, ENAME, JOB FROM EMP
WHERE EMPNO > 980;

SELECT SAL, ENAME FROM EMP;

SELECT ENAME, SAL FROM EMP
WHERE SAL = 3000;

SELECT ENAME, SAL FROM EMP
WHERE SAL*12 > 36000;

SELECT * FROM EMP;

SELECT * FROM EMP
WHERE SAL > 2000
AND MGR > 7800;

SELECT * FROM EMP;

SELECT * FROM EMP
WHERE JOB = 'ANALYST'
AND SAL >= 2500;

SELECT * FROM EMP
WHERE ENAME >= '%F%';

SELECT * FROM EMP
WHERE SAL != 3000;

SELECT * FROM EMP
WHERE SAL <> 3000;

SELECT * FROM EMP
WHERE NOT SAL = 3000;

SELECT ENAME, JOB FROM EMP
WHERE JOB = 'CLERK'
OR JOB = 'SALESMAN'
OR JOB = 'ANALYST';


SELECT ENAME, JOB FROM EMP
WHERE JOB IN ('CLERK','SALESMAN','ANALYST');

SELECT ENAME, JOB FROM EMP
WHERE JOB NOT IN ('CLERK','SALESMAN','ANALYST');

SELECT * FROM EMP;

SELECT * FROM EMP
WHERE DEPTNO IN ('10','20');

SELECT * FROM EMP
WHERE SAL > 2000
AND SAL < 3000;

SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000
ORDER BY SAL DESC;

SELECT * FROM EMP
WHERE ENAME LIKE 'S%';

SELECT * FROM EMP
WHERE ENAME LIKE '%S';

SELECT * FROM EMP
WHERE ENAME LIKE '%S%';

SELECT * FROM EMP
WHERE ENAME LIKE '%T';

SELECT * FROM EMP
WHERE ENAME LIKE '%T';

SELECT * FROM EMP
WHERE ENAME LIKE '%S%'
OR ENAME LIKE '%T%';

SELECT * FROM EMP
WHERE ENAME LIKE '%S%'
OR ENAME LIKE '%T%';

SELECT * FROM EMP
WHERE ENAME LIKE '_L%';

SELECT * FROM EMP
WHERE ENAME LIKE '%L%';

SELECT * FROM EMP
WHERE ENAME LIKE '_C%';

SELECT * FROM EMP
WHERE COMM IS NULL;

SELECT * FROM EMP
WHERE COMM IS NOT NULL;

SELECT * FROM EMP
WHERE SAL > NULL;

SELECT * FROM EMP
WHERE SAL IS NULL;

SELECT * FROM EMP
WHERE SAL IS NOT NULL;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20
ORDER BY DEPTNO ASC;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20
ORDER BY DEPTNO ASC;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20
ORDER BY DEPTNO ASC;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, DEPTNO, SAL
FROM EMP
WHERE DEPTNO = 20
ORDER BY DEPTNO DESC;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20
ORDER BY SAL ASC;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;



SELECT * FROM EMP
WHERE ENAME LIKE '%S';

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = '30'
AND JOB = 'SALESMAN';


SELECT * FROM EMP
WHERE DEPTNO IN ('20','30')
AND SAL > 2000;

--SMITH의 직속 상관의 이름을 출력하시오.
SELECT ENAME FROM EMP
WHERE EMPNO IN(SELECT MGR FROM EMP
                WHERE ENAME = 'SMITH');


SELECT ENAME, MGR, HIREDATE, JOB FROM EMP
WHERE ENAME = 'SMITH'
ORDER BY SAL DESC;

DESC SALGRADE;

DESC EMP;

SELECT DEPTNO
FROM EMP;


SELECT ENAME, SAL, SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+COMM, COMM
FROM EMP;

SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM
FROM EMP;

SELECT * FROM EMP;

SELECT ENAME, SAL * 12 FROM EMP;

SELECT ENAME AS 이름, SAL * 12 AS SAL_YEAR, COMM FROM EMP;

SELECT ENAME, EMPNO, DEPTNO FROM EMP;

SELECT * FROM EMP;

SELECT ENAME, EMPNO, DEPTNO FROM EMP
WHERE DEPTNO IN ('10','20')
ORDER BY DEPTNO ASC;

SELECT ENAME, EMPNO FROM EMP
ORDER BY EMPNO ASC;

SELECT DISTINCT JOB FROM EMP;

SELECT * FROM EMP
WHERE EMPNO = 7499
AND DEPTNO = 30;