SELECT *
    FROM EMP
    WHERE SAL < ANY (SELECT SAL
        FROM EMP
        WHERE DEPTNO = 30)
    ORDER BY SAL, EMPNO;
   
SELECT *
    FROM EMP
    WHERE SAL < ALL (SELECT SAL
        FROM EMP
        WHERE DEPTNO = 30)
    ORDER BY SAL, EMPNO;
   
SELECT *
    FROM EMP
    WHERE EXISTS (SELECT DNAME
        FROM DEPT
        WHERE DEPTNO = 10);
       
SELECT *
    FROM EMP
    WHERE HIREDATE < ALL (
        SELECT HIREDATE
        FROM EMP
        WHERE DEPTNO = 10
    );
   
/*다중열 서브쿼리*/
SELECT *
    FROM EMP
    WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
        FROM EMP
        GROUP BY DEPTNO);
       
SELECT DEPTNO, SAL
    FROM EMP;
   
/*인라인 뷰*/
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
    FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
        (SELECT * FROM DEPT) D
        WHERE E10.DEPTNO = D.DEPTNO;

/*전체 사원 중 ALLEN과 같은 직책인 사원들의 사원 정보, 부서 정보를 다음과 같이
출력하는 SQL문을 작성하세요.*/      
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    AND JOB IN (
        SELECT JOB
        FROM DEPT
        WHERE E.ENAME = 'ALLEN'
    );
   
/*전체 사원의 평균 급여보다 높은 급여를 받는 사원들의 사원 정보, 부서 정보, 급여 등급
정보를 출력하는 SQL문을 작성하세요*/
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
    FROM EMP E, DEPT D, SALGRADE S
    WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL > (
        SELECT AVG(SAL)
        FROM EMP
    )
    AND E.SAL BETWEEN LOSAL AND HISAL;
   
SELECT *
    FROM EMP E, DEPT D, SALGRADE S
    WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND SAL > (SELECT AVG(SAL) FROM EMP);
   
---------------------------------------------------
/*DML, DDL, 트랜잭션 공부*/

CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT
    WHERE DEPTNO = 50;
   
DROP TABLE DEPT_TEMP;
   
SELECT *
    FROM DEPT_TEMP;

/*EMPNO, ENAME, JOB 칼럼만 가지는 EMP 테이블의 복사본을 만드시오*/    
CREATE TABLE EMP_TEMP
    AS SELECT EMPNO, ENAME, JOB
    FROM EMP;
   
SELECT * FROM EMP_TEMP;

DROP TABLE EMP_TEMP;

/*부서가 20번인 사원정보가 들어있는 EMPNO, ENAME, JOB 칼럼을 가지는
EMP_TEMP 테이블을 만들어 봅니다*/
CREATE TABLE EMP_TEMP
    AS SELECT EMPNO, ENAME, JOB
    FROM EMP
    WHERE DEPTNO = 20;
   
SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB)
    VALUES (4444, 'HIHI', 'NOJOB');
   
SELECT * FROM EMP_TEMP;

--INSERT문 오류가 발생
INSER INTO EMP_TEMP(DEPTNO, DNAME, LOC)
    VALUES(60, 'NETWORK');
   
INSERT INTO EMP_TEMP (DEPTNO, DNAME, LOC)
    VALUES(60, 'NETWROK', 'BUSAN', 'WRONG');
   
INSERT INTO EMP_TEMP (DEPTNO, DNAME, LOC)
    VALUES('WRONG', 'NETWORK', 'BUSAN');
   
INSRET INTO EMP_TEMP (DEPTNO, DNAME, LOC)
    VALUES (600, 'NETWORK', 'BUSAN');
   
--INSERT문에 열 지정 없이 데이터 추가하기
INSERT INTO EMP_TEMP
    VALUES(60, 'NETWORK', 'BUSAN');
   
SELECT * FROM EMP_TEMP;

--NULL의 명시적 입력
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
    VALUES(70, 'WEB', NULL);
   
CREATE TABLE DEPT_TEMP
    AS SELECT DEPTNO, DNAME, LOC FROM DEPT;
   
DROP TABLE DEPTNO_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
    VALUES(80, 'MOBILE', '');
   
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, LOC)
    VALUES (90, 'INCHEON');

--서브쿼리로 여러 데이터 추가하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE = 1;

--데이터 수정하기
CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;
   
UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE',
    LOC = 'SEOUL'
    WHERE DEPTNO = 40;
   
SELECT * FROM DEPT_TEMP;

UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE',
        LOC = 'BUSAN'
        WHERE DEPTNO = 40;
       
    SELECT * FROM DEPT_TEMP2;
   
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL';
   
SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
    SET DEPTNO = 40,
    DNAME = 'DATABASE',
    LOC = 'BUSAN'
    WHERE DEPTNO = 20;
   
ROLLBACK;

INSERT INTO DEPT_TEMP
    VALUES (20, 'SALES', NULL);
   
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
    VALUES (20, 'SEOUL');
   
SELECT * FROM DEPT_TEMP;

UPDATE DEPT_TEMP
    SET LOC = 'BUSAN'
    WHERE LOC = 'SEOUL';
   
CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP;
   
SELECT * FROM DEPT_TEMP;

UPDATE EMP_TEMP
    SET COMM = 50
    WHERE SAL <= 2500;

SELECT * FROM EMP_TEMP;
ROLLBACK;

COMMIT;

INSERT INTO DEPT_TEMP (DEPTNO, LOC)
    VALUES (20, 'BUSAN');
   
--COMMIT과 ROLLBACK은 DML(INSERT, UPDATE, DELETE) 에만 적용됨

DROP TABLE DEPT_TEMP2;

CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
    SET (DNAME, LOC) = (SELECT DNAME, LOC
                        FROM DEPT
                        WHERE DEPTNO = 30)
    WHERE DEPTNO = 40;
COMMIT;

UPDATE DEPT_TEMP2
    SET (DNAME, LOC) = (SELECT DNAME, LOC
                        FROM DEPT
                        WHERE DEPTNO = 20)
    WHERE DEPTNO BETWEEN 10 AND 40;
   
SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL'
    WHERE DEPTNO = (SELECT DEPTNO
                    FROM DEPT
                    WHERE DNAME = 'OPERATIONS');

ROLLBACK;
SELECT * FROM DEPT_TEMP2;

DROP TABLE EMP_TEMP;

CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP;
   
DELETE FROM EMP_TEMP
    WHERE JOB = 'MANAGER';

DELETE FROM EMP_TEMP
    WHERE SAL >= 3000;
   
ROLLBACK;

/*오른쪽과 같이 테이블에 50, 60 ,70, 80번 부서를 등록하는
SQL을 작성하세요*/

CREATE TABLE DEPT_TCL
    AS SELECT * FROM DEPT;

DELETE FROM DEPT_TCL
    WHERE DEPTNO = 40;
   
SELECT * FROM DEPT_TCL;

COMMIT;

UPDATE DEPT_TCL
    SET LOC = 'SEOUL'
    WHERE DEPTNO = 30;
COMMIT;

CREATE TABLE EMP_PRACTICE
    AS SELECT * FROM EMP;
   
DROP TABLE EMP_PRACTICE;

--모든 열의 각 자료형을 정의해서 테이블 생성하기
CREATE TABLE EMP_DDL(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE    DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
    );
   
SELECT * FROM DEPT_TEMP;
DROP TABLE DEPT_TEMP;

CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;
   
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;
   
SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);
   
CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);
   
CREATE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
        FROM EMP
        WHERE DEPTNO = 20);
       
SELECT *
    FROM USER_VIEWS;
   
SELECT *
    FROM VW_EMP20;
   
CREATE VIEW VM_EMP30ALL
    AS (SELECT *
        FROM EMP
        WHERE DEPTNO = 30);
       
SELECT *
    FROM VM_EMP30ALL;